services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  postgres:
    image: postgres:16.3
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres-2_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spredis
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres-2_data: